[sdl]
autolock=false
usescancodes=true

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cputype=auto
cycles=fixed @CYCLES@

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[render]
frameskip=0
aspect=false
scaler=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
oplmode=opl2

[speaker]
pcspeaker=true

[joystick]
joysticktype=2axis

[serial]
serial1=disabled
serial2=disabled

[autoexec]
@echo off
mount c .
c:
@AUTOEXEC@
